2021-12-14 10:42:54[main:0]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginCmd====org.tinygame.herostory.cmdHandler.PlayerLoginCmdHandler
2021-12-14 10:42:54[main:52]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableCmd====org.tinygame.herostory.cmdHandler.CleanTableCmdHandler
2021-12-14 10:42:54[main:520]-[INFO] ---------------
2021-12-14 10:42:54[main:521]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginCmd <=> 10001
2021-12-14 10:42:54[main:522]-[INFO] ---------------
2021-12-14 10:42:54[main:522]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginRet <=> 10002
2021-12-14 10:42:54[main:533]-[INFO] ---------------
2021-12-14 10:42:54[main:533]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableCmd <=> 10003
2021-12-14 10:42:54[main:534]-[INFO] ---------------
2021-12-14 10:42:54[main:534]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableRet <=> 10004
2021-12-14 10:42:56[main:2638]-[INFO] 服务器启动成功
2021-12-14 10:51:57[MainThreadProcessor:543573]-[INFO] userName = leon1
2021-12-14 10:51:57[AsyncOperationProcessor1:543609]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 10:51:58[MainThreadProcessor:544067]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 10:51:58[MainThreadProcessor:544067]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 10:56:22[MainThreadProcessor:808262]-[INFO] userName = leon1
2021-12-14 10:56:22[AsyncOperationProcessor1:808264]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 10:56:22[AsyncOperationProcessor1:808282]-[ERROR] 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 264,377 milliseconds ago. The last packet sent successfully to the server was 264,378 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
### The error may exist in org/tinygame/herostory/login/db/IUserDao.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT user_id, puid, `password`, hero_avatar, cash, money, gold FROM t_user WHERE puid = ?;
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 264,377 milliseconds ago. The last packet sent successfully to the server was 264,378 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 264,377 milliseconds ago. The last packet sent successfully to the server was 264,378 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
### The error may exist in org/tinygame/herostory/login/db/IUserDao.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT user_id, puid, `password`, hero_avatar, cash, money, gold FROM t_user WHERE puid = ?;
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 264,377 milliseconds ago. The last packet sent successfully to the server was 264,378 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:93)
	at com.sun.proxy.$Proxy6.getUserByName(Unknown Source)
	at org.tinygame.herostory.login.LoginService$AsyncGetUserByName.doAsync(LoginService.java:89)
	at org.tinygame.herostory.async.AsyncOperationProcessor.lambda$process$1(AsyncOperationProcessor.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 264,377 milliseconds ago. The last packet sent successfully to the server was 264,378 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 12 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 264,377 milliseconds ago. The last packet sent successfully to the server was 264,378 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:570)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:625)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
	... 21 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
	at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:561)
	... 25 more
2021-12-14 10:56:22[MainThreadProcessor:808285]-[ERROR] 用户登录失败, userName = leon1
2021-12-14 10:56:59[MainThreadProcessor:845565]-[INFO] userName = leon1
2021-12-14 10:56:59[AsyncOperationProcessor1:845565]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 10:56:59[MainThreadProcessor:845571]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 10:56:59[MainThreadProcessor:845572]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 11:00:51[MainThreadProcessor:1077034]-[INFO] userName = leon1
2021-12-14 11:00:51[AsyncOperationProcessor1:1077034]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 11:00:51[AsyncOperationProcessor1:1077035]-[ERROR] 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 231,464 milliseconds ago. The last packet sent successfully to the server was 231,465 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
### The error may exist in org/tinygame/herostory/login/db/IUserDao.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT user_id, puid, `password`, hero_avatar, cash, money, gold FROM t_user WHERE puid = ?;
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 231,464 milliseconds ago. The last packet sent successfully to the server was 231,465 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 231,464 milliseconds ago. The last packet sent successfully to the server was 231,465 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
### The error may exist in org/tinygame/herostory/login/db/IUserDao.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT user_id, puid, `password`, hero_avatar, cash, money, gold FROM t_user WHERE puid = ?;
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 231,464 milliseconds ago. The last packet sent successfully to the server was 231,465 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:93)
	at com.sun.proxy.$Proxy6.getUserByName(Unknown Source)
	at org.tinygame.herostory.login.LoginService$AsyncGetUserByName.doAsync(LoginService.java:89)
	at org.tinygame.herostory.async.AsyncOperationProcessor.lambda$process$1(AsyncOperationProcessor.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 231,464 milliseconds ago. The last packet sent successfully to the server was 231,465 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 12 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 231,464 milliseconds ago. The last packet sent successfully to the server was 231,465 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:570)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:625)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
	... 21 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
	at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:561)
	... 25 more
2021-12-14 11:00:51[MainThreadProcessor:1077036]-[ERROR] 用户登录失败, userName = leon1
2021-12-14 11:01:02[MainThreadProcessor:1088631]-[INFO] userName = leon1
2021-12-14 11:01:02[AsyncOperationProcessor1:1088631]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 11:01:02[MainThreadProcessor:1088639]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 11:01:02[MainThreadProcessor:1088639]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 11:13:44[MainThreadProcessor:1850370]-[INFO] userName = leon1
2021-12-14 11:13:44[AsyncOperationProcessor1:1850371]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 11:13:44[AsyncOperationProcessor1:1850372]-[ERROR] 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 761,733 milliseconds ago. The last packet sent successfully to the server was 761,733 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
### The error may exist in org/tinygame/herostory/login/db/IUserDao.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT user_id, puid, `password`, hero_avatar, cash, money, gold FROM t_user WHERE puid = ?;
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 761,733 milliseconds ago. The last packet sent successfully to the server was 761,733 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 761,733 milliseconds ago. The last packet sent successfully to the server was 761,733 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
### The error may exist in org/tinygame/herostory/login/db/IUserDao.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT user_id, puid, `password`, hero_avatar, cash, money, gold FROM t_user WHERE puid = ?;
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 761,733 milliseconds ago. The last packet sent successfully to the server was 761,733 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:93)
	at com.sun.proxy.$Proxy6.getUserByName(Unknown Source)
	at org.tinygame.herostory.login.LoginService$AsyncGetUserByName.doAsync(LoginService.java:89)
	at org.tinygame.herostory.async.AsyncOperationProcessor.lambda$process$1(AsyncOperationProcessor.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 761,733 milliseconds ago. The last packet sent successfully to the server was 761,733 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 12 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 761,733 milliseconds ago. The last packet sent successfully to the server was 761,733 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:570)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:625)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:941)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
	... 21 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
	at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:561)
	... 25 more
2021-12-14 11:13:44[MainThreadProcessor:1850373]-[ERROR] 用户登录失败, userName = leon1
2021-12-14 11:20:13[main:0]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginCmd====org.tinygame.herostory.cmdHandler.PlayerLoginCmdHandler
2021-12-14 11:20:13[main:18]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableCmd====org.tinygame.herostory.cmdHandler.CleanTableCmdHandler
2021-12-14 11:20:13[main:379]-[INFO] ---------------
2021-12-14 11:20:13[main:381]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginCmd <=> 10001
2021-12-14 11:20:13[main:381]-[INFO] ---------------
2021-12-14 11:20:13[main:382]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginRet <=> 10002
2021-12-14 11:20:13[main:385]-[INFO] ---------------
2021-12-14 11:20:13[main:385]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableCmd <=> 10003
2021-12-14 11:20:13[main:385]-[INFO] ---------------
2021-12-14 11:20:13[main:386]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableRet <=> 10004
2021-12-14 11:20:16[main:2872]-[INFO] 服务器启动成功
2021-12-14 11:23:14[MainThreadProcessor:181232]-[INFO] userName = leon1
2021-12-14 11:23:14[AsyncOperationProcessor1:181258]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 11:23:14[AsyncOperationProcessor1:181553]-[WARN] Execution of ping query 'select now() from classes limit 1' failed: Table 'hero_story.classes' doesn't exist
2021-12-14 11:23:14[MainThreadProcessor:181560]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 11:23:14[MainThreadProcessor:181560]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 17:56:41[main:0]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginCmd====org.tinygame.herostory.cmdHandler.PlayerLoginCmdHandler
2021-12-14 17:56:41[main:31]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableCmd====org.tinygame.herostory.cmdHandler.CleanTableCmdHandler
2021-12-14 17:56:42[main:772]-[INFO] ---------------
2021-12-14 17:56:42[main:774]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginCmd <=> 10001
2021-12-14 17:56:42[main:774]-[INFO] ---------------
2021-12-14 17:56:42[main:774]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginRet <=> 10002
2021-12-14 17:56:42[main:778]-[INFO] ---------------
2021-12-14 17:56:42[main:779]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableCmd <=> 10003
2021-12-14 17:56:42[main:779]-[INFO] ---------------
2021-12-14 17:56:42[main:779]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableRet <=> 10004
2021-12-14 17:56:44[main:2876]-[INFO] 服务器启动成功
2021-12-14 17:57:57[MainThreadProcessor:75415]-[INFO] userName = leon1
2021-12-14 17:57:57[AsyncOperationProcessor1:75438]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 17:57:57[MainThreadProcessor:75768]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 17:57:57[MainThreadProcessor:75768]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 17:58:08[MainThreadProcessor:86445]-[INFO] table number = 1<=>21
2021-12-14 18:04:50[MainThreadProcessor:488196]-[INFO] userName = leon1
2021-12-14 18:04:50[AsyncOperationProcessor1:488196]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 18:04:50[MainThreadProcessor:488198]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 18:04:50[MainThreadProcessor:488198]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 18:04:51[MainThreadProcessor:489494]-[INFO] table number = 1<=>21
2021-12-14 18:14:15[MainThreadProcessor:1054121]-[INFO] userName = leon1
2021-12-14 18:14:16[AsyncOperationProcessor1:1054136]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 18:14:16[MainThreadProcessor:1054142]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 18:14:16[MainThreadProcessor:1054142]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 18:14:33[MainThreadProcessor:1071652]-[INFO] table number = 1<=>21
2021-12-14 18:15:09[MainThreadProcessor:1108040]-[INFO] userName = leon1
2021-12-14 18:15:09[AsyncOperationProcessor1:1108040]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 18:15:09[MainThreadProcessor:1108042]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 18:15:09[MainThreadProcessor:1108042]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 18:15:17[MainThreadProcessor:1115935]-[INFO] table number = 1<=>21
2021-12-14 18:16:19[MainThreadProcessor:1177814]-[INFO] userName = leon1
2021-12-14 18:16:19[AsyncOperationProcessor1:1177814]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 18:16:19[MainThreadProcessor:1177816]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 18:16:19[MainThreadProcessor:1177816]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 18:18:11[MainThreadProcessor:1289390]-[INFO] table number = 1<=>21
2021-12-14 18:33:12[main:0]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginCmd====org.tinygame.herostory.cmdHandler.PlayerLoginCmdHandler
2021-12-14 18:33:12[main:78]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableCmd====org.tinygame.herostory.cmdHandler.CleanTableCmdHandler
2021-12-14 18:33:13[main:415]-[INFO] ---------------
2021-12-14 18:33:13[main:416]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginCmd <=> 10001
2021-12-14 18:33:13[main:417]-[INFO] ---------------
2021-12-14 18:33:13[main:417]-[INFO] org.tinygame.herostory.msg.PlayerProto$PlayerLoginRet <=> 10002
2021-12-14 18:33:13[main:421]-[INFO] ---------------
2021-12-14 18:33:13[main:421]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableCmd <=> 10003
2021-12-14 18:33:13[main:421]-[INFO] ---------------
2021-12-14 18:33:13[main:422]-[INFO] org.tinygame.herostory.msg.TableProto$CleanTableRet <=> 10004
2021-12-14 18:33:15[main:2507]-[INFO] 服务器启动成功
2021-12-14 18:33:22[MainThreadProcessor:9480]-[INFO] userName = leon1
2021-12-14 18:33:22[AsyncOperationProcessor1:9494]-[INFO] 当前线程 = AsyncOperationProcessor1
2021-12-14 18:33:22[MainThreadProcessor:9758]-[INFO] 当前线程 = MainThreadProcessor
2021-12-14 18:33:22[MainThreadProcessor:9758]-[INFO] 用户登陆成功; userId = 6, puid = leon1
2021-12-14 18:33:36[MainThreadProcessor:23821]-[INFO] table number = 1<=>21
2021-12-14 18:34:02[MainThreadProcessor:49486]-[INFO] table number = 1<=>21
2021-12-14 18:34:10[MainThreadProcessor:57646]-[INFO] table number = 1<=>21
2021-12-14 18:34:17[MainThreadProcessor:64484]-[INFO] table number = 1<=>21
2021-12-14 18:34:18[MainThreadProcessor:65996]-[INFO] table number = 1<=>21
2021-12-14 18:34:19[MainThreadProcessor:66420]-[INFO] table number = 1<=>21
2021-12-14 18:34:19[MainThreadProcessor:66749]-[INFO] table number = 1<=>21
2021-12-14 18:34:19[MainThreadProcessor:67066]-[INFO] table number = 1<=>21
2021-12-14 18:34:20[MainThreadProcessor:67408]-[INFO] table number = 1<=>21
2021-12-14 18:34:20[MainThreadProcessor:67690]-[INFO] table number = 1<=>21
2021-12-14 18:34:20[MainThreadProcessor:68017]-[INFO] table number = 1<=>21
2021-12-14 18:34:21[MainThreadProcessor:68323]-[INFO] table number = 1<=>21
2021-12-14 18:36:33[MainThreadProcessor:200305]-[INFO] table number = 1<=>21
2021-12-14 18:36:34[MainThreadProcessor:201159]-[INFO] table number = 1<=>21
